top5 <- read.table("household_power_consumption.txt",sep=";",header=TRUE,nrows=5)
classes <- sapply(top5,class)
df <- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.string = "?",colClasses = classes)
df$Date <- as.Date(df$Date,format='%d/%m/%Y')
df.subset <- subset(df,Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
## df.subset$Time <- as.POSIXct(paste(df.subset$Date,df.subset$Time),format="%Y-%m-%d %H:%M:%S")
png("plot1.png",width=480,height=480)
hist(df.subset$Global_active_power,col="red",main= "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()